name: Workflow CI FirahMaulida Bintang 5 Final

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
          
      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0 dagshub pandas scikit-learn matplotlib seaborn

      - name: Run MLflow Project
        env:
          # KUNCINYA DI SINI: Semua aplikasi (CLI & Python) pakai env yang sama
          MLFLOW_TRACKING_URI: "https://dagshub.com/firahmaulida/Eksperimen_SML_FirahMaulida.mlflow"
          MLFLOW_TRACKING_USERNAME: "firahmaulida"
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          # Jalankan tanpa --experiment-name di sini agar lebih stabil
          # Nama experiment sudah ada di file MLProject atau default
          mlflow run MLProject --env-manager local
