name: Workflow CI FirahMaulida Bintang 5 Final

on:
  push:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.12.7"
  DOCKER_IMAGE_NAME: "firahmaulida/telco-churn-mlflow"

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0 dagshub pandas scikit-learn matplotlib seaborn

      - name: Set DagsHub Secrets
        run: |
          echo "MLFLOW_TRACKING_USERNAME=firahmaulida" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGSHUB_TOKEN }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/firahmaulida/Eksperimen_SML_FirahMaulida.mlflow" >> $GITHUB_ENV

      - name: Run MLflow Project
        run: |
          # Perintah paling stabil: jalankan MLflow project
          mlflow run MLProject --env-manager local --experiment-name "Telco_Churn_CI_FirahMaulida"

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: model-results
          path: MLProject/
